/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;
/**
 *
 * @author cdgn2
 */
public class FrameAdmin extends javax.swing.JFrame {

    private Autorizar autorizar = new Autorizar();
    private Reasignar reasignar = new Reasignar();
    private Informe informe = new Informe();
    /**
     * Creates new form FrameUsuario
     */
    public FrameAdmin()
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalAdminPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        autorizarB = new javax.swing.JButton();
        reasignarB = new javax.swing.JButton();
        informeB = new javax.swing.JButton();
        cerrarSesionB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principalAdminPanel.setMinimumSize(new java.awt.Dimension(700, 500));
        principalAdminPanel.setLayout(new java.awt.BorderLayout());

        menuPanel.setBackground(new java.awt.Color(9, 12, 2));
        menuPanel.setToolTipText("");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Grupo 3.1.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(9, 12, 2));
        jPanel3.setPreferredSize(new java.awt.Dimension(119, 196));
        jPanel3.setLayout(new java.awt.GridLayout(4, 0));

        autorizarB.setBackground(new java.awt.Color(9, 12, 2));
        autorizarB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        autorizarB.setForeground(new java.awt.Color(255, 255, 255));
        autorizarB.setText("AUTORIZAR");
        autorizarB.setBorder(null);
        autorizarB.setBorderPainted(false);
        autorizarB.setFocusable(false);
        autorizarB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        autorizarB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        autorizarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorizarBActionPerformed(evt);
            }
        });
        jPanel3.add(autorizarB);

        reasignarB.setBackground(new java.awt.Color(9, 12, 2));
        reasignarB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        reasignarB.setForeground(new java.awt.Color(255, 255, 255));
        reasignarB.setText("REASIGNAR");
        reasignarB.setBorder(null);
        reasignarB.setBorderPainted(false);
        reasignarB.setFocusable(false);
        reasignarB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reasignarB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reasignarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasignarBActionPerformed(evt);
            }
        });
        jPanel3.add(reasignarB);

        informeB.setBackground(new java.awt.Color(9, 12, 2));
        informeB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        informeB.setForeground(new java.awt.Color(255, 255, 255));
        informeB.setText("INFORME");
        informeB.setBorder(null);
        informeB.setBorderPainted(false);
        informeB.setFocusable(false);
        informeB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        informeB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        informeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeBActionPerformed(evt);
            }
        });
        jPanel3.add(informeB);

        cerrarSesionB.setBackground(new java.awt.Color(9, 12, 2));
        cerrarSesionB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        cerrarSesionB.setForeground(new java.awt.Color(255, 255, 255));
        cerrarSesionB.setText("CERRAR SESIÓN");
        cerrarSesionB.setBorder(null);
        cerrarSesionB.setBorderPainted(false);
        cerrarSesionB.setFocusable(false);
        cerrarSesionB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrarSesionB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cerrarSesionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBActionPerformed(evt);
            }
        });
        jPanel3.add(cerrarSesionB);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(principalAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(principalAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autorizarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorizarBActionPerformed
        // TODO add your handling code here:
        principalAdminPanel.setVisible(false);
        principalAdminPanel.removeAll();
        principalAdminPanel.add(autorizar);
        principalAdminPanel.setVisible(true);
        autorizar.showUsersinTable();
    }//GEN-LAST:event_autorizarBActionPerformed

    private void reasignarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasignarBActionPerformed
        // TODO add your handling code here:
        principalAdminPanel.setVisible(false);
        principalAdminPanel.removeAll();
        principalAdminPanel.add(reasignar);
        principalAdminPanel.setVisible(true);
        reasignar.showUsersinTable();
    }//GEN-LAST:event_reasignarBActionPerformed

    private void informeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeBActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        principalAdminPanel.setVisible(false);
        principalAdminPanel.removeAll();
        principalAdminPanel.add(informe);
        principalAdminPanel.setVisible(true);
    }//GEN-LAST:event_informeBActionPerformed

    private void cerrarSesionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBActionPerformed
        this.setVisible(false);
        PrincipalFrame principalFrame = new PrincipalFrame();
        principalFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarSesionBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autorizarB;
    private javax.swing.JButton cerrarSesionB;
    private javax.swing.JButton informeB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel principalAdminPanel;
    private javax.swing.JButton reasignarB;
    // End of variables declaration//GEN-END:variables
}
