/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;
/**
 *
 * @author cdgn2
 */
public class FrameAdmin extends javax.swing.JFrame {

    private Autorizar autorizar = new Autorizar();
    private Reasignar reasignar = new Reasignar();
    private Informe informe = new Informe();
    /**
     * Creates new form FrameUsuario
     */
    public FrameAdmin()
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        autorizarB = new javax.swing.JButton();
        reasignarB = new javax.swing.JButton();
        informeB = new javax.swing.JButton();
        cerrarSesionB = new javax.swing.JButton();
        principalAdminPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        autorizarB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        autorizarB.setText("Autorizar");
        autorizarB.setFocusable(false);
        autorizarB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        autorizarB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        autorizarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorizarBActionPerformed(evt);
            }
        });
        jToolBar1.add(autorizarB);

        reasignarB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        reasignarB.setText("Reasignar");
        reasignarB.setFocusable(false);
        reasignarB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reasignarB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reasignarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasignarBActionPerformed(evt);
            }
        });
        jToolBar1.add(reasignarB);

        informeB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        informeB.setText("Informe");
        informeB.setFocusable(false);
        informeB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        informeB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        informeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informeBActionPerformed(evt);
            }
        });
        jToolBar1.add(informeB);

        cerrarSesionB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        cerrarSesionB.setText("Cerrar Sesión");
        cerrarSesionB.setFocusable(false);
        cerrarSesionB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrarSesionB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cerrarSesionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBActionPerformed(evt);
            }
        });
        jToolBar1.add(cerrarSesionB);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        principalAdminPanel.setMinimumSize(new java.awt.Dimension(650, 500));
        principalAdminPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(principalAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(principalAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void autorizarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorizarBActionPerformed
        // TODO add your handling code here:
        principalAdminPanel.setVisible(false);
        principalAdminPanel.removeAll();
        principalAdminPanel.add(autorizar);
        principalAdminPanel.setVisible(true);
    }//GEN-LAST:event_autorizarBActionPerformed

    private void reasignarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasignarBActionPerformed
        // TODO add your handling code here:
        principalAdminPanel.setVisible(false);
        principalAdminPanel.removeAll();
        principalAdminPanel.add(reasignar);
        principalAdminPanel.setVisible(true);
    }//GEN-LAST:event_reasignarBActionPerformed

    private void informeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informeBActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        principalAdminPanel.setVisible(false);
        principalAdminPanel.removeAll();
        principalAdminPanel.add(informe);
        principalAdminPanel.setVisible(true);
    }//GEN-LAST:event_informeBActionPerformed

    private void cerrarSesionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBActionPerformed
        this.setVisible(false);
        PrincipalFrame principalFrame = new PrincipalFrame();
        principalFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarSesionBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton autorizarB;
    private javax.swing.JButton cerrarSesionB;
    private javax.swing.JButton informeB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel principalAdminPanel;
    private javax.swing.JButton reasignarB;
    // End of variables declaration//GEN-END:variables
}
