/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import DAO.CitaDAO;
import DAO.SucursalDAO;
import DAO.UsuarioDAO;
import Entidad.Cita;
import Entidad.Usuario;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author cdgn2
 */
public class FrameUsuario extends javax.swing.JFrame {

    private Usuario usuario; //Para facilitar se le pasa el usuario que ingreso sesion.
    private Agendar agendar;
    private Citaciones citas;
    private UsuarioDAO udao = new UsuarioDAO();
    private CitaDAO cdao = new CitaDAO();
    private ArrayList<Cita> citasList = (ArrayList<Cita>) cdao.obtener();

    int estado = 0;

    /**
     * Creates new form FrameUsuario
     */
    public FrameUsuario(Usuario u) {
        this.usuario = u;
        System.out.println(usuario.toString());
        agendar = new Agendar(usuario);
        citas = new Citaciones(usuario);
        initComponents();
        setLocationRelativeTo(null);

        
        List<Usuario> usuarios = udao.obtener();
        for (Usuario a : usuarios) {
            if (a.getUsuario().equals(usuario.getUsuario())) { //No deberian haber dos nombres de usuario iguales
                usuario = a;
                break;
            }
        }

        for (int i = 0; i < citasList.size(); i++) {

            if (citasList.get(i).getUsuario().getIdentificacion() == this.usuario.getIdentificacion()) {
                Cita aux = citasList.get(i);

                if (aux.getEstado() == 6) {
                    ReasignarPopUp1 pop = new ReasignarPopUp1();
                    pop.setVisible(true);
                    
                }
                break;
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        agendarB = new javax.swing.JButton();
        citacionesB = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        cerrarSesionB = new javax.swing.JButton();
        principalUsuarioPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        agendarB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        agendarB.setText("Agendar");
        agendarB.setFocusable(false);
        agendarB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agendarB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agendarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendarBActionPerformed(evt);
            }
        });
        jToolBar1.add(agendarB);

        citacionesB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        citacionesB.setText("Citaciones");
        citacionesB.setFocusable(false);
        citacionesB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        citacionesB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        citacionesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citacionesBActionPerformed(evt);
            }
        });
        jToolBar1.add(citacionesB);
        jToolBar1.add(filler1);

        cerrarSesionB.setText("Cerrar Sesión");
        cerrarSesionB.setFocusable(false);
        cerrarSesionB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cerrarSesionB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cerrarSesionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSesionBActionPerformed(evt);
            }
        });
        jToolBar1.add(cerrarSesionB);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        principalUsuarioPanel.setMinimumSize(new java.awt.Dimension(500, 650));
        principalUsuarioPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(principalUsuarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(principalUsuarioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agendarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendarBActionPerformed
        // TODO add your handling code here:
        principalUsuarioPanel.setVisible(false);
        principalUsuarioPanel.removeAll();
        principalUsuarioPanel.add(agendar);
        principalUsuarioPanel.setVisible(true);
    }//GEN-LAST:event_agendarBActionPerformed

    private void citacionesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citacionesBActionPerformed
        // TODO add your handling code here:
        principalUsuarioPanel.setVisible(false);
        principalUsuarioPanel.removeAll();
        principalUsuarioPanel.add(citas);
        principalUsuarioPanel.setVisible(true);
        citas.showUsersinTable();
    }//GEN-LAST:event_citacionesBActionPerformed

    private void cerrarSesionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSesionBActionPerformed
        this.setVisible(false);
        PrincipalFrame principalFrame = new PrincipalFrame();
        principalFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrarSesionBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendarB;
    private javax.swing.JButton cerrarSesionB;
    private javax.swing.JButton citacionesB;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel principalUsuarioPanel;
    // End of variables declaration//GEN-END:variables
}
