
package Frontera;

import Entidad.Sistema;
import Entidad.Usuario;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class PrincipalFrame extends javax.swing.JFrame {

    public Ingreso ingreso;
    //private Agendar agendar = new Agendar();
    
    public static Sistema sistema = new Sistema();
    
    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();
        
        ingreso = new Ingreso(this, principalPanel);
        
        principalPanel.setVisible(false);
        principalPanel.removeAll();
        principalPanel.add(ingreso);
        principalPanel.setVisible(true);
        
        //JFrame.setDefaultLookAndFeelDecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        principalPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank App");
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(900, 557));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 35)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Grupo 2.1.png"))); // NOI18N
        jLabel2.setAlignmentX(0.5F);
        jPanel1.add(jLabel2);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bancolombia.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentX(0.5F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMinimumSize(new java.awt.Dimension(332, 178));
        jLabel1.setPreferredSize(new java.awt.Dimension(332, 178));
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);

        principalPanel.setBackground(new java.awt.Color(116, 79, 198));
        principalPanel.setPreferredSize(new java.awt.Dimension(600, 500));
        principalPanel.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(principalPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel principalPanel;
    // End of variables declaration//GEN-END:variables
}
