
package Frontera;

import Entidad.Sistema;
import Entidad.Usuario;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class PrincipalFrame extends javax.swing.JFrame {

    public Registro registro = new Registro();
    public Ingreso ingreso = new Ingreso(this);
    //private Agendar agendar = new Agendar();
    
    public static Sistema sistema = new Sistema();
    
    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();
        //inicializacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        ingresoB = new javax.swing.JButton();
        registroB = new javax.swing.JButton();
        principalPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        ingresoB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        ingresoB.setText("Ingreso");
        ingresoB.setFocusable(false);
        ingresoB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ingresoB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ingresoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoBActionPerformed(evt);
            }
        });
        jToolBar1.add(ingresoB);

        registroB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        registroB.setText("Registro");
        registroB.setFocusable(false);
        registroB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registroB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        registroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroBActionPerformed(evt);
            }
        });
        jToolBar1.add(registroB);

        principalPanel.setPreferredSize(new java.awt.Dimension(600, 500));
        principalPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(principalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoBActionPerformed
        // TODO add your handling code here:
        principalPanel.setVisible(false);
        principalPanel.removeAll();
        principalPanel.add(ingreso);
        //principalPanel.add(agendar);
        principalPanel.setVisible(true);
    }//GEN-LAST:event_ingresoBActionPerformed

    private void registroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroBActionPerformed
        // TODO add your handling code here:
        principalPanel.setVisible(false);
        principalPanel.removeAll();
        principalPanel.add(registro);
        principalPanel.setVisible(true);
    }//GEN-LAST:event_registroBActionPerformed
    
    /*
    public void inicializacion(){
        
        ArrayList<Usuario> usuarios;
        usuarios = new ArrayList<>();
        
        Usuario a = new Usuario("Juan", "Cardona", 1010038260,"juan","1234",false);
        Usuario b = new Usuario("Pedro", "Nieto", 1010038259,"pedro","1234567",false);
        Usuario c = new Usuario("Maria del Mar", "Rojas", 1010038258,"maria","12345",false);
        Usuario d = new Usuario("Carlos", "Galvis", 1010038257,"CarlosKC26","Carlosdgn2000",true);
        
        
        usuarios.add(a);
        usuarios.add(b);
        usuarios.add(c);
        usuarios.add(d);
        
        sistema.setUsuarios(usuarios);
        
        for (Usuario u: sistema.getUsuarios()){
            System.out.println(u.getUsuario());
            System.out.println(u.getContrasenia());
            System.out.println("--------------");
                    
        }
    }
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresoB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JButton registroB;
    // End of variables declaration//GEN-END:variables
}
